// Generated by CoffeeScript 1.9.1
module.exports = (function(_this) {
  return function(grunt) {
    var port;
    require('load-grunt-tasks')(grunt);
    port = 9000 + ((Math.random() * 10) | 0);
    grunt.initConfig({
      appSettings: {
        port: port
      },
      connect: {
        server: {
          options: {
            livereload: true,
            base: 'app/',
            port: '<%= appSettings.port %>'
          }
        }
      },
      open: {
        server: {
          path: 'http://localhost:<%= appSettings.port %>',
          app: 'Google Chrome'
        }
      },
      watch: {
        options: {
          livereload: true
        },
        html: {
          files: 'app/**/*.html'
        },
        css: {
          files: 'app/**/*.css'
        },
        scripts: {
          files: 'app/**/*.js'
        }
      }
    });
    grunt.registerTask('serve', ['connect', 'open', 'watch']);
    return grunt.registerTask('default', ['serve']);
  };
})(this);
